insert into publishers (id, name) values (1, 'Becker, O''Keefe and Dicki');
insert into publishers (id, name) values (2, 'Bartell-Kuvalis');
insert into publishers (id, name) values (3, 'Fadel Group');
insert into publishers (id, name) values (4, 'Stanton Inc');
insert into publishers (id, name) values (5, 'Gerlach, Berge and Lynch');
insert into publishers (id, name) values (6, 'Green-Keeling');
insert into publishers (id, name) values (7, 'West-Rolfson');
insert into publishers (id, name) values (8, 'Nicolas-Towne');
insert into publishers (id, name) values (9, 'Will, Konopelski and Dare');
insert into publishers (id, name) values (10, 'Moen-Kuphal');
insert into publishers (id, name) values (11, 'Huels, Feeney and Conroy');
insert into publishers (id, name) values (12, 'Padberg LLC');
insert into publishers (id, name) values (13, 'O''Connell-Mohr');
insert into publishers (id, name) values (14, 'Corkery and Sons');
insert into publishers (id, name) values (15, 'Labadie-Lockman');
insert into publishers (id, name) values (16, 'Padberg, Borer and Wehner');
insert into publishers (id, name) values (17, 'Runte-Wyman');
insert into publishers (id, name) values (18, 'Hoppe and Sons');
insert into publishers (id, name) values (19, 'White, Renner and Bednar');
insert into publishers (id, name) values (20, 'Walter LLC');
