insert into subCategories (id, name, categoryId) values (1, 'historia del arte', 1);
insert into subCategories (id, name, categoryId) values (2, 'música', 1);
insert into subCategories (id, name, categoryId) values (3, 'cine y video', 1);
insert into subCategories (id, name, categoryId) values (4, 'fotografía', 1);
insert into subCategories (id, name, categoryId) values (5, 'infantil', 5);
insert into subCategories (id, name, categoryId) values (6, 'juvenil', 5);
insert into subCategories (id, name, categoryId) values (7, 'novelas', 6);
insert into subCategories (id, name, categoryId) values (8, 'clásicos', 6);
insert into subCategories (id, name, categoryId) values (9, 'ciencia ficción', 6);
insert into subCategories (id, name, categoryId) values (10, 'terror', 6);
insert into subCategories (id, name, categoryId) values (11, 'policiales', 6);
insert into subCategories (id, name, categoryId) values (12, 'cuentos o relatos', 6);
insert into subCategories (id, name, categoryId) values (13, 'cómics', 7);
insert into subCategories (id, name, categoryId) values (14, 'novelas gráficas', 7);
